AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'lib/tasks/**'
    - 'Gemfile'
  Excludes:
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'bin/*'
    - 'app/controllers/admin/concerns/*'
    - 'lib/templates/**/*'
    - spec/**/*
    - db/schema.rb
    - 'config/initializers/**'

Style/AndOr:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: exploded

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Lint/EachWithObjectArgument:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_email_like
    - find_by_key
    - find_by_anonymized_phrase

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'db/seeds.rb'
    - 'config/routes.rb'
    - 'vendor/**/*'

Metrics/ClassLength:
  CountComments: false
  Max: 210

Style/RegexpLiteral:
  Enabled: false

Metrics/ModuleLength:
  CountComments: false
  Max: 205

Metrics/MethodLength:
  Max: 20
  CountComments: false

Metrics/AbcSize:
  Max: 30

Rails:
  Enabled: true
