development:
  adapter: postgresql
  encoding: unicode
  database: rubbricks_dev
  pool: 5
  username: antonio.serna
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rubbricks_test
  pool: 5
  username: antonio.serna
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rubbricks_production
  pool: 5
  username: antonio.serna
  password: